// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZAu4zXFtut7UfGecHG7nWWJZZ2hP7iV8',
    appId: '1:886666155527:android:f5a31c114d459009257ca2',
    messagingSenderId: '886666155527',
    projectId: 'cinemate-6bf27',
    storageBucket: 'cinemate-6bf27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_FVOKyBCSsfMojPh64vUBKzu67pWyw3c',
    appId: '1:886666155527:ios:ce84e4bcaafbb97d257ca2',
    messagingSenderId: '886666155527',
    projectId: 'cinemate-6bf27',
    storageBucket: 'cinemate-6bf27.firebasestorage.app',
    iosBundleId: 'com.example.nail',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS0fnwX7NIb9_Ppih3i0qQmZjoJl2o9H0',
    appId: '1:886666155527:web:75bbcf2e09b12e8d257ca2',
    messagingSenderId: '886666155527',
    projectId: 'cinemate-6bf27',
    authDomain: 'cinemate-6bf27.firebaseapp.com',
    storageBucket: 'cinemate-6bf27.firebasestorage.app',
  );

}