// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIT2nu7B78WUtD-4ydOkV-1-vzUbJbvm0',
    appId: '1:832254727467:web:341a33dbb708b31954616e',
    messagingSenderId: '832254727467',
    projectId: 'artsync-561f5',
    authDomain: 'artsync-561f5.firebaseapp.com',
    storageBucket: 'artsync-561f5.firebasestorage.app',
    measurementId: 'G-X35T04L0W6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5bZ5hcMvCo7ntaCFJHpd2e-8hvOboFQA',
    appId: '1:832254727467:android:5709d4b4ec70c67a54616e',
    messagingSenderId: '832254727467',
    projectId: 'artsync-561f5',
    storageBucket: 'artsync-561f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJh9pwjv7eZJaQtx1hNtyztZUuT9UXK5k',
    appId: '1:832254727467:ios:9de2d47f78a4007254616e',
    messagingSenderId: '832254727467',
    projectId: 'artsync-561f5',
    storageBucket: 'artsync-561f5.firebasestorage.app',
    iosBundleId: 'com.example.nail',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJh9pwjv7eZJaQtx1hNtyztZUuT9UXK5k',
    appId: '1:832254727467:ios:9de2d47f78a4007254616e',
    messagingSenderId: '832254727467',
    projectId: 'artsync-561f5',
    storageBucket: 'artsync-561f5.firebasestorage.app',
    iosBundleId: 'com.example.nail',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIT2nu7B78WUtD-4ydOkV-1-vzUbJbvm0',
    appId: '1:832254727467:web:219a982f1c3dbb4754616e',
    messagingSenderId: '832254727467',
    projectId: 'artsync-561f5',
    authDomain: 'artsync-561f5.firebaseapp.com',
    storageBucket: 'artsync-561f5.firebasestorage.app',
    measurementId: 'G-PC6DXW5ZM7',
  );
}
